### ISSUE TITLE
BOLOS on a HSM

### ISSUE THREAD

**Issue by AusExHaw** [LedgerHQ/bolos-enclave#2]
Hi BTChip,

We have access to the Gemalto HSM described in your BOLOS Solution here.

https://www.ledger.fr/2016/08/08/how-to-properly-secure-cryptocurrencies-exchanges/

We would like to licence the BOLOS O/S for use in the Gemalto HSM as described above. I understand that this is a close relative to this BOLOS-Enclave but is closed source. 

We would really like to talk to someone in relation to getting access to the Gemalto HSM version of this.

Thanks in Advance.

**Comment by btchip** [comment]
Hi 

Can you contact vault@ledger.fr ? Thanks
